
CREATE TABLE IF NOT EXISTS privates (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user1_id INTEGER NOT NULL,
	user2_id INTEGER NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(user1_id, user2_id),
	CHECK(user1_id < user2_id),
	FOREIGN KEY(user1_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY(user2_id) REFERENCES users(id) ON DELETE CASCADE
);
